CREATE TABLE "GEN_DCR_TYPE" (
"DCR_TYPE_NO"  INTEGER NOT NULL,
"DCR_TYPE"  TEXT(500) NOT NULL,
"DCR_TYPE_CODE"  TEXT(100) NOT NULL,
PRIMARY KEY ("DCR_TYPE_NO")
);
CREATE TABLE "GEN_USER_TYPES" (
"USER_TYPE_NO"  INTEGER NOT NULL,
"USER_TYPE"  TEXT(500) NOT NULL,
"SHORT_NAME"  TEXT(100),
"IS_ACTIVE"  INTEGER,
PRIMARY KEY ("USER_TYPE_NO")
);
CREATE TABLE "SEC_USERS" (
"USER_NO"  INTEGER NOT NULL,
"USER_TYPE_NO"  INTEGER NOT NULL,
"DEPT_NO"  INTEGER,
"DEPT_NAME"  TEXT(500),
"COMP_NO"  INTEGER,
"COMP_NAME"  TEXT(500),
"DESIG_NO"  INTEGER,
"DESIG_NAME"  TEXT(500),
"HR_EMP_ID"  TEXT(500) NOT NULL,
"USER_FULL_NAME"  TEXT(500),
"USER_NICK_NAME"  TEXT(500),
"USER_MOBILE"  TEXT(100) NOT NULL,
"IS_ACTIVE"  INTEGER,
"ACTIVE_FROM"  REAL,
"ACTIVE_TO"  REAL,
PRIMARY KEY ("USER_NO")
);
CREATE TABLE "SEC_USER_THANA" (
"USER_THANA_NO"  INTEGER NOT NULL,
"THANA_NO"  INTEGER NOT NULL,
"USER_NO"  INTEGER NOT NULL,
"IS_ACTIVE"  INTEGER,
"ACTIVE_FROM"  REAL,
"ACTIVE_TO"  REAL,
PRIMARY KEY ("USER_THANA_NO")
);
CREATE TABLE "SET_CLASS" (
"CLASS_NO"  INTEGER NOT NULL,
"CLASS_NAME"  TEXT(500) NOT NULL,
"CLASS_NAME_BNG"  TEXT(500),
"IS_ACTIVE"  INTEGER,
"ACTIVE_FROM"  REAL,
"ACTIVE_TO"  REAL,
PRIMARY KEY ("CLASS_NO")
);
CREATE TABLE "SET_CLIENT_INFO" (
"CLIENT_NO"  INTEGER NOT NULL,
"CLIENT_NAME"  TEXT(500),
"CLIENT_NAME_BNG"  TEXT(500),
"CLIENT_NICK_NAME"  TEXT(500),
"CLIENT_MOBILE"  TEXT(100) NOT NULL,
"DIVISION_NO"  INTEGER,
"ZONE_NO"  INTEGER,
"ZILLA_NO"  INTEGER,
"THANA_NO"  INTEGER,
"IS_ACTIVE"  INTEGER,
"ACTIVE_FROM"  REAL,
"ACTIVE_TO"  REAL,
PRIMARY KEY ("CLIENT_NO")
);
CREATE TABLE "SET_DIVISION" (
"DIVISION_NO"  INTEGER NOT NULL,
"DIVISION_NAME"  TEXT(500) NOT NULL,
"DIVISION_NAME_BNG"  TEXT(500),
"DIVISION_CODE"  TEXT(100),
"IS_ACTIVE"  INTEGER,
"ACTIVE_FROM"  REAL,
"ACTIVE_TO"  REAL,
PRIMARY KEY ("DIVISION_NO")
);
CREATE TABLE "SET_EXP_TYPE" (
"EXP_TYPE_NO"  INTEGER NOT NULL,
"EXP_TYPE_NAME"  TEXT(500) NOT NULL,
"EXP_TYPE_CODE"  TEXT(100),
"IS_ACTIVE"  INTEGER,
"ACTIVE_FROM"  REAL,
"ACTIVE_TO"  REAL,
PRIMARY KEY ("EXP_TYPE_NO")
);
CREATE TABLE "SET_INSTITUTE" (
"INSTITUTE_NO"  INTEGER NOT NULL,
"INSTITUTE_NAME"  TEXT(500) NOT NULL,
"INSTITUTE_NAME_BNG"  TEXT(500),
"INST_TYPE_NO"  INTEGER,
"THANA_NO"  INTEGER,
"F_INSTITUTION_DB_ID"  TEXT(500),
"EIIN_NUMBER"  TEXT(100),
"MEET_PERSON_NAME"  TEXT(500),
"CONTACT_NUMBER"  TEXT(500),
"ACTUAL_LATI_VAL"  INTEGER,
"ACTUAL_LONG_VAL"  INTEGER,
"FROM_LATI_VAL"  INTEGER,
"FROM_LONG_VAL"  INTEGER,
"TO_LATI_VAL"  INTEGER,
"TO_LONG_VAL"  INTEGER,
"IS_ACTIVE"  INTEGER,
"ACTIVE_FROM"  REAL,
"ACTIVE_TO"  REAL,
PRIMARY KEY ("INSTITUTE_NO" ASC)
);
CREATE TABLE "SET_INST_TYPE" (
"INST_TYPE_NO"  INTEGER NOT NULL,
"INST_TYPE_NAME"  TEXT(500) NOT NULL,
"INST_TYPE_CODE"  TEXT(50),
"IS_ACTIVE"  INTEGER,
"ACTIVE_FROM"  REAL,
"ACTIVE_TO"  REAL,
PRIMARY KEY ("INST_TYPE_NO")
);
CREATE TABLE "SET_ORG_TYPE" (
"ORG_TYPE_NO"  INTEGER NOT NULL,
"ORG_TYPE_NAME"  TEXT(500) NOT NULL,
"ORG_TYPE_CODE"  TEXT(100),
"IS_ACTIVE"  INTEGER,
"ACTIVE_FROM"  REAL,
"ACTIVE_TO"  REAL,
PRIMARY KEY ("ORG_TYPE_NO")
);
CREATE TABLE "SET_PROMO_ITEM" (
"PROMO_ITEM_NO"  INTEGER NOT NULL,
"PROMO_ITEM_NAME"  TEXT(500) NOT NULL,
"PROMO_ITEM_CODE"  TEXT(100),
"PROMO_ITEM_TYPE_NO"  INTEGER,
"IS_ACTIVE"  INTEGER,
"ACTIVE_FROM"  REAL,
"ACTIVE_TO"  REAL,
PRIMARY KEY ("PROMO_ITEM_NO")
);
CREATE TABLE "SET_SPECIMEN" (
"SPECIMEN_NO"  INTEGER NOT NULL,
"SPECIMEN_NAME"  TEXT(500) NOT NULL,
"SPECIMEN_NAME_BNG"  TEXT(500),
"SPECIMEN_CODE"  TEXT(100),
"BOOK_TYPE_NO"  INTEGER,
"BOOK_UNIQUE_CODE"  TEXT(100),
"IS_ACTIVE"  INTEGER,
"ACTIVE_FROM"  REAL,
"ACTIVE_TO"  REAL,
PRIMARY KEY ("SPECIMEN_NO")
);
CREATE TABLE "SET_SUBJECT" (
"SUBJECT_NO"  INTEGER NOT NULL,
"SUBJECT_NAME"  TEXT(500) NOT NULL,
"SUBJECT_NAME_BNG"  TEXT(500),
"SUBJECT_CODE"  TEXT(50),
"IS_ACTIVE"  INTEGER,
"ACTIVE_FROM"  REAL,
"ACTIVE_TO"  REAL,
PRIMARY KEY ("SUBJECT_NO")
);
CREATE TABLE "SET_TEACHER_DESIG" (
"TEACH_DESIG_NO"  INTEGER NOT NULL,
"TEACHER_DESIG_NAME"  TEXT(500) NOT NULL,
"TEACHER_DESIG_NAME_BNG"  TEXT(500),
"IS_ACTIVE"  INTEGER,
"ACTIVE_FROM"  REAL,
"ACTIVE_TO"  REAL,
PRIMARY KEY ("TEACH_DESIG_NO")
);
CREATE TABLE "SET_TEACHER_INFO" (
"TEACHER_NO"  INTEGER NOT NULL,
"TEACHER_NAME"  TEXT(500) NOT NULL,
"TEACHER_NAME_BNG"  TEXT(500),
"TEACHER_NICK_NAME"  TEXT(500),
"TEACHER_MOBILE"  TEXT(100) NOT NULL,
"INSTITUTE_NO"  INTEGER NOT NULL,
"TEACH_DESIG_NO"  INTEGER,
"IS_ACTIVE"  INTEGER,
"ACTIVE_FROM"  REAL,
"ACTIVE_TO"  REAL,
PRIMARY KEY ("TEACHER_NO")
);
CREATE TABLE "SET_THANA" (
"THANA_NO"  INTEGER NOT NULL,
"ZONE_NO"  INTEGER NOT NULL,
"ZILLA_NO"  INTEGER NOT NULL,
"THANA_NAME"  TEXT(500) NOT NULL,
"THANA_NAME_BNG"  TEXT(500),
"THANA_CODE"  TEXT(100),
"IS_ACTIVE"  INTEGER,
"ACTIVE_FROM"  REAL,
"ACTIVE_TO"  REAL,
PRIMARY KEY ("THANA_NO")
);
CREATE TABLE "SET_TRANSPORT_TYPE" (
"TRANS_TYPE_NO"  INTEGER NOT NULL,
"TRANS_TYPE_NAME"  TEXT(500) NOT NULL,
"TRANS_TYPE_CODE"  TEXT(100),
"IS_ACTIVE"  INTEGER,
"ACTIVE_FROM"  REAL,
"ACTIVE_TO"  REAL,
PRIMARY KEY ("TRANS_TYPE_NO")
);
CREATE TABLE "SET_WORK_PURPOSE" (
"WORK_PUR_NO"  INTEGER NOT NULL,
"WORK_PUR_NAME"  TEXT(500) NOT NULL,
"WORK_PUR_CODE"  TEXT(100),
"IS_ACTIVE"  INTEGER,
"ACTIVE_FROM"  REAL,
"ACTIVE_TO"  REAL,
PRIMARY KEY ("WORK_PUR_NO")
);
CREATE TABLE "SET_ZILLA" (
"ZILLA_NO"  INTEGER NOT NULL,
"DIVISION_NO"  INTEGER NOT NULL,
"ZILLA_NAME"  TEXT(500) NOT NULL,
"ZILLA_NAME_BNG"  TEXT(500),
"ZILLA_CODE"  TEXT,
"IS_ACTIVE"  INTEGER,
"ACTIVE_FROM"  REAL,
"ACTIVE_TO"  REAL,
PRIMARY KEY ("ZILLA_NO")
);
CREATE TABLE "SET_ZONE" (
"ZONE_NO"  INTEGER NOT NULL,
"DIVISION_NO"  INTEGER NOT NULL,
"ZONE_NAME"  TEXT(500) NOT NULL,
"ZONE_NAME_BNG"  TEXT(500),
"ZONE_CODE"  TEXT(100),
"ZONE_GRADE"  TEXT(500),
"IS_ACTIVE"  INTEGER,
"ACTIVE_FROM"  REAL,
"ACTIVE_TO"  REAL,
PRIMARY KEY ("ZONE_NO")
);
CREATE TABLE "TRN_DCR" (
"OFFLINE_DCR_NO"  INTEGER NOT NULL,
"ACTION_OFFLINE_TIME"  TEXT(70) NOT NULL,
"DCR_TYPE_NO"  INTEGER NOT NULL,
"IS_REF_ZM"  INTEGER,
"REF_ZM_USER_NO"  INTEGER,
"REF_ZM_MOBILE"  TEXT(100),
"WORK_AREA_FROM_LAT"  REAL,
"WORK_AREA_FROM_LON"  REAL,
"WORK_AREA_FROM_NAME"  TEXT(500),
"WORK_AREA_TO_LAT"  REAL,
"WORK_AREA_TO_LON"  REAL,
"WORK_AREA_TO_NAME"  TEXT(500),
"TIME_FROM"  TEXT(70),
"TIME_TO"  TEXT(70),
"TIME_GAP"  TEXT(70),
"INSTITUTE_NO"  INTEGER,
"TRANS_TYPE_NO"  INTEGER,
"FARE_AMT"  REAL,
"TRN_DCR_DATE"  TEXT(50),
"IS_MANUAL_ENTRY"  INTEGER DEFAULT 0,
"COMMENTS"  TEXT(1000),
"ENTRY_STATE"  INTEGER DEFAULT 1,
"IS_UPLOADED"  INTEGER DEFAULT 0,
"IS_COMPLETE_NEW"  INTEGER DEFAULT 1,
"USER_NO"  INTEGER NOT NULL,
PRIMARY KEY ("OFFLINE_DCR_NO" ASC)
);
CREATE TABLE "TRN_DCR_DET" (
"OFFLINE_DCR_DET_NO"  INTEGER NOT NULL,
"OFFLINE_DCR_NO"  INTEGER NOT NULL,
"ACTION_OFFLINE_TIME"  TEXT(70),
"IS_FOR_TEACHER"  INTEGER,
"TEACHER_NO"  INTEGER,
"TEACHER_MOBILE"  TEXT(100),
"SPECIMEN_NO"  INTEGER,
"SPECIMEN_QTY"  INTEGER,
"IS_FOR_CLIENT"  INTEGER,
"CLIENT_NO"  INTEGER,
"CLIENT_MOBILE"  TEXT(100),
"PROMO_ITEM_NO"  INTEGER,
"PROMO_ITEM_QTY"  INTEGER,
"ENTRY_STATE"  INTEGER DEFAULT 1,
"IS_UPLOADED"  INTEGER DEFAULT 0,
"IS_COMPLETE_NEW"  INTEGER DEFAULT 1,
"IS_ON_BEHALF"  INTEGER DEFAULT 0,
"BEHALF_MOBILE"  TEXT(100),
"BEHALF_NICK" TEXT(100),
"TEACHER_NICK" TEXT(100),
PRIMARY KEY ("OFFLINE_DCR_DET_NO")
);
CREATE TABLE "TRN_EXPENSE" (
"OFFLINE_EXP_NO"  INTEGER NOT NULL,
"ACTION_OFFLINE_TIME"  TEXT(50) NOT NULL,
"TRN_EXP_DATE"  TEXT(50),
"IS_MANUAL_ENTRY"  INTEGER DEFAULT 0,
"ENTRY_STATE"  INTEGER DEFAULT 1,
"IS_UPLOADED"  INTEGER DEFAULT 0,
"IS_COMPLETE_NEW"  INTEGER DEFAULT 1,
"USER_NO"  INTEGER NOT NULL,
PRIMARY KEY ("OFFLINE_EXP_NO" ASC)
);
CREATE TABLE "TRN_EXPENSE_DET" (
"OFFLINE_EXP_DET_NO"  INTEGER NOT NULL,
"OFFLINE_EXP_NO"  INTEGER NOT NULL,
"ACTION_OFFLINE_TIME"  TEXT(50) NOT NULL,
"EXP_TYPE_NO"  INTEGER NOT NULL,
"EXP_AMT"  REAL DEFAULT 0,
"LAT_VAL"  REAL,
"LON_VAL"  REAL,
"VENDOR"  TEXT(300),
"COMMENTS"  TEXT(1000),
"ENTRY_STATE"  INTEGER DEFAULT 1,
"IS_UPLOADED"  INTEGER DEFAULT 0,
"IS_COMPLETE_NEW"  INTEGER DEFAULT 1,
PRIMARY KEY ("OFFLINE_EXP_DET_NO" ASC)
);
CREATE TABLE "TRN_MSG" (
"MSG_NO"  INTEGER NOT NULL,
"FROM_USER_NO"  INTEGER NOT NULL,
"USER_TYPE_NO"  INTEGER NOT NULL,
"USER_FULL_NAME"  TEXT(500) NOT NULL,
"USER_MOBILE"  TEXT(100),
"USER_TYPE"  TEXT(500),
"MSG_SUBJECT"  TEXT(500) NOT NULL,
"MSG_BODY"  TEXT(1000) NOT NULL,
"IS_REPLY_ALLOW"  INTEGER,
"REF_MSG_NO"  INTEGER,
"IS_REPLY"  INTEGER,
"MSG_REC_NO"  INTEGER,
"REC_USER_NO"  INTEGER,
"IS_READ"  INTEGER,
"INSERT_TIME" TEXT(100),
PRIMARY KEY ("MSG_NO")
);
CREATE TABLE "TRN_USER_LOCATION" (
"OFFLINE_LOC_NO"  INTEGER NOT NULL,
"ACTION_OFFLINE_TIME"  TEXT(50) NOT NULL,
"LAT_VAL"  REAL NOT NULL,
"LON_VAL"  REAL NOT NULL,
"LOCATION_NAME"  TEXT(500) NOT NULL,
"ENTRY_STATE"  INTEGER DEFAULT 1,
"IS_UPLOADED"  INTEGER DEFAULT 0,
"IS_COMPLETE_NEW"  INTEGER DEFAULT 1,
"USER_NO"  INTEGER NOT NULL,
PRIMARY KEY ("OFFLINE_LOC_NO")
);
CREATE TABLE "TRN_USER_PROMO_DET" (
"USER_PROMO_DET_NO"  INTEGER NOT NULL,
"USER_PROMO_NO"  INTEGER NOT NULL,
"PROMO_ITEM_CODE"  TEXT(100),
"PROMO_ITEM_NAME"  TEXT(500) NOT NULL,
"PROMO_ITEM_NO"  INTEGER NOT NULL,
"QTY"  INTEGER NOT NULL,
"IS_ACTIVE"  INTEGER,
PRIMARY KEY ("USER_PROMO_DET_NO")
);
CREATE TABLE "TRN_USER_PROMO_ITEM" (
"USER_PROMO_NO"  INTEGER NOT NULL,
"USER_NO"  INTEGER NOT NULL,
"ASSIGN_DATE"  TEXT(50),
"TARGET_DATE_FROM"  TEXT(50),
"TARGET_DATE_TO"  TEXT(50),
"IS_ACTIVE"  INTEGER,
PRIMARY KEY ("USER_PROMO_NO")
);
CREATE TABLE "TRN_USER_SPECIMEN" (
"USER_SPECIMEN_NO"  INTEGER NOT NULL,
"USER_NO"  INTEGER NOT NULL,
"ASSIGN_DATE"  TEXT(50) NOT NULL,
"TARGET_DATE_FROM"  TEXT(50),
"TARGET_DATE_TO"  TEXT(50),
"IS_ACTIVE"  INTEGER,
PRIMARY KEY ("USER_SPECIMEN_NO")
);
CREATE TABLE "TRN_USER_SPECIMEN_DET" (
"SPECIMEN_DET_NO"  INTEGER NOT NULL,
"USER_SPECIMEN_NO"  INTEGER NOT NULL,
"SPECIMEN_CODE"  TEXT(100) NOT NULL,
"SPECIMEN_NAME"  TEXT(500),
"SPECIMEN_NAME_BNG"  TEXT(500),
"SPECIMEN_NO"  INTEGER NOT NULL,
"QTY"  INTEGER,
"IS_ACTIVE"  INTEGER,
PRIMARY KEY ("SPECIMEN_DET_NO")
);
CREATE TABLE "TRN_USER_FEED_BACK"(
"OFFLINE_FEEDBACK_NO" INTEGER NOT NULL ,
"ACTION_OFFLINE_TIME" TEXTACTION_OFF,
"USER_NO" INTEGER,
"FEEDBACK_TYPE_NO" INTEGER,
"MESSAGE" TEXT(500),
"ENTRY_STATE" INTEGER DEFAULT 1,
"IS_UPLOADED" INTEGER DEFAULT 0,
PRIMARY KEY("OFFLINE_FEEDBACK_NO")
);
CREATE TABLE "SET_FEEDBACK_TYPE"(
"FEEDBACK_TYPE_NO" INTEGER NOT NULL , 
"FEEDBACK_NAME" TEXT(100), 
"FEEDBACK_CODE" TEXT(100), 
"FEEDBACK_DESC" TEXT(500), 
"IS_ACTIVE" INTEGER, 
"ACTIVE_FROM" REAL, 
"ACTIVE_TO" REAL,
PRIMARY KEY("FEEDBACK_TYPE_NO")
);
CREATE TABLE "LOGIN_INFO"(
"USER_NO" INTEGER NOT NULL,
"LOCATION_NAME" TEXT(200),
"TIME" TEXT(100),
"LONGITUDE" TEXT(100),
"LATITUDE" TEXT(100),
PRIMARY KEY("USER_NO")
);